// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvyiouutgyzhmoiuqxly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2eWlvdXV0Z3l6aG1vaXVxeGx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTk5NTEsImV4cCI6MjA2MzM5NTk1MX0.QSUDXaX_smyZT1noTXjeCnzGL4QCroxR8c26LSVQVBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);